### ISSUE TITLE
Problem with private includes

### ISSUE THREAD

**Issue by mnil** [martis42/depend_on_what_you_use#100] opened 2023-02-14 07:40 UTC
I think a regression was introduced in a31db72c46fd2be0c9bd95100ee37de515f4a98d and is not working on latest.

We have the following module:
```
$ tree foo/
foo/
├── BUILD.bazel
├── foo.h
└── src
    ├── foobar.h
    └── foo.cpp
```

```
$ cat foo/BUILD.bazel 
cc_library(
    name = "foo",
    srcs = [
        "src/foo.cpp",
        "src/foobar.h",
    ],
    hdrs = [
        "foo.h",
    ],
    deps = [],
)
```
```
$ cat foo/src/foo.cpp 
#include "foo/foo.h"

#include "foobar.h"
// #include "foo/src/foobar.h"  // changing to this makes it work again.

int foobar()
{
    return 42;
}
```

```
================================================================================
DWYU analyzing: '@//foo:foo'

Result: FAILURE

Includes which are not available from the direct dependencies:
  File='foo/src/foo.cpp', include='foobar.h'
================================================================================
```

This worked fine in f2ecd055874eb77e2eb9a30cb0e7ba2fd9e838db. Was this change intentional or unintentional?

**Comment by martis42** [comment] 2023-02-14 21:23
Hi @mnil 
This is a regression. Your example is supposed to work. I will look into this.

**Comment by martis42** [comment] 2023-02-19 10:11
@mnil 
Found the bug. Essentially, the latest changes ignored that it is valid to use header files listed in `srcs` with relative includes (where using headers from `srcs` of dependencies is forbidden).
Will push a fix as soon as I manage to extend the relative include test cases.

**Comment by martis42** [comment] 2023-02-19 22:17
Issue has been released and a new release with the fix has been deployed

**Comment by mnil** [comment] 2023-02-21 09:42
I have now verified that this solves our problem, thanks for the quick fix!

**Comment by MatthiasU** [comment] 2024-07-31 06:51
Hi @martis42 !

Thx for you work to improve dependency resolution within bezel projects 👍🏼 ! 
I think this popped up again. In one of my projects I have following structure:

```
BUILD
include/
       foo.h
src/
      foo.cpp
      private_bar.h
      private_bar.cpp
```

The tool throws an "private include without deps" error 

Could that be another regression ? I use version 0.4.0 (assumed the latest right now) 

Thx !

**Comment by martis42** [comment] 2024-09-01 09:15
@MatthiasU friendly ping

**Comment by martis42** [comment] 2024-09-16 19:56
closing due to no reproducible report existing

**Closed by martis42** 2024-09-16 19:56 UTC
