### ISSUE TITLE
Quote include of file in same directory failing to be found

### ISSUE THREAD

**Issue by mjj47** [martis42/depend_on_what_you_use#85] opened 2023-01-12 05:12 UTC
This time, repro'ed within DWYU test case :) 

looks like if you have a single build rule with two headers in sub directories, one including the other, DWYU doesn't find the locally sourced header.

Tested with:
bazel build   --aspects=//my_awesome:aspect.bzl%your_dwyu_aspect --output_groups=cc_dwyu_output --override_repository=depend_on_what_you_use=/home/michael.johnson/code/depend_on_what_you_use @depend_on_what_you_use//test/aspect/includes:includes2

[0001-Add-relative-include.patch](https://github.com/martis42/depend_on_what_you_use/files/10398363/0001-Add-relative-include.patch)

**Comment by storypku** [comment] 2023-01-12 21:28
Confirmed that `bazel build :include2` succeeded while `bazel build --config=dwyu` failed.
the content of deps_info.json:
```
{
	"self": {
		"headers": [
			"dir/includes.h",
			"dir/includes2.h",
		],
		"target": "@//test/aspect/includes:includes2"
	}
```
Changing either `#include "includes.h"` to `#include "dir/includes.h"` in includes2.h or add 
`some/sub/dir` to the `includes` for `includes2` in the BUILD file will make DWYU happy.

So the issue for this case is, should the current directory taken into account by default,
even if it wasn't specified via `includeds` ?

**Comment by martis42** [comment] 2023-01-12 22:05
Thanks for reporting this issue. Processing such relative includes should indeed work and consequently this is a bug in DWYU.
Theoretically this feature is already supported. A basic tests exists [here](https://github.com/martis42/depend_on_what_you_use/blob/main/test/aspect/valid/bar/bar.cc). Those relative includes are detected correctly. It seems though there are still open edge cases.

I will look into this as soon as I have some spare time.

**Comment by storypku** [comment] 2023-01-15 02:35
At first glance, @mjj47 's case can be addressed by simply adding the following line after [dwyu.bzl#70](https://github.com/martis42/depend_on_what_you_use/blob/d1ac79f2ebff4fcb1225348bef03406abe2ba275/src/aspect/dwyu.bzl#L70):

```
includes.append(hdr.path.rpartition("/")[-1])
```
However, it wouldn't cover cases like the following

```
$ cat > foo.h <<EOF
cat foo.h 
#ifndef FOO_H_
#define FOO_H_
int foo();
#endif // FOO_H_
<<EOF
$ cat > foo.cc <<EOF
#include "foo.h"
int foo() { return 42; }
EOF
$ cat > main.cc <<EOF
#include "foo.h"
int main() {
    return foo();
}
<<EOF
$ cat > BUILD <<EOF
cc_library(
    name = "foo",
    srcs = ["foo.cc"],
    hdrs = ["foo.h"],
)
cc_binary(
   name = "use_foo",
   srcs = ["main.cc"],
   deps = [":foo"],
)
EOF
```

To handle the case above, we seem to add the following line after [dwyu.bzl#52](https://github.com/martis42/depend_on_what_you_use/blob/d1ac79f2ebff4fcb1225348bef03406abe2ba275/src/aspect/dwyu.bzl#L52), which will cover both @mjj47 's case and the case above.

However, this may raise another issue, What if two `dep`s (listed in a target's `deps` section or from transitive deps) providing two headers with the same basename? What should we do in this situation?

This is the situations what best practices means:
> 1. Make all include paths relative to the workspace directory. 
>  -- From [Bazel's best practice for C++](https://bazel.build/docs/bazel-and-cpp#include-paths)
> 2. Include the directory when naming header files. 
> -- From [cpplint/cpplint:cpplint.py](https://github.com/cpplint/cpplint/blob/fa12a0bbdafa15291276ddd2a2dcd2ac7a2ce4cb/cpplint.py#L5094).

**Comment by martis42** [comment] 2023-01-21 21:53
I did some investigation into this issue.
The more I look into this, the more complex it becomes. On a first glance the solutions presented by @storypku seem to resolve the issue. But one can create more complex examples for which they no longer work (e.g. relative includes into sub directories).

The problem seems solvable to me. But I expect it requires a rewrite of the "relative includes" logic to work more general on the file system locations of the header files.

**Comment by martis42** [comment] 2023-01-26 22:34
I have locally a prototype which seems to handle this issue
There are still some quirks which have to be resolved and code refactored. I have no ETA due to being quite busy with other things. But fixing this issue is in steady, albeit slow, progress.

**Comment by martis42** [comment] 2023-02-03 22:40
The issue should now be resolved with these changes https://github.com/martis42/depend_on_what_you_use/issues

In the next days I will create also a new release containing this fix

**Closed by martis42** 2023-02-03 22:40 UTC
