### ISSUE TITLE
ignore_include_paths hits include libraries that contain the substring

### ISSUE THREAD

**Issue by matte1** [martis42/depend_on_what_you_use#66] opened 2022-12-02 23:12 UTC
I'm trying to add "array" to the ignore_include_paths; however, this then causes issues with a custom include that also contains array in the name. I think it would be a simple fix to instead check the strings for equality, but this might break peoples current work flow. Wanted to open a discussion on what the best way to fix this would be!

**Comment by martis42** [comment] 2022-12-03 09:24
Thanks for reporting this.

I consider this a bug.
The desired behavior is to either ignore a full include path or a pattern. However, given the current implementation every string is interpreted as a substring pattern, meaning `array` will match `array_foo`.

I am thinking about changing the interface for ignoring include paths. One dedicated for concrete include paths, where we essentially use string equality in the impl and one dedicated to include path patterns using the current impl. 

Alternatively one could try to dynamically infer if a string is supposed to be a full include path or a pattern. But given most "normal" strings are also valid input to python regex, I don't think there is a stable way to do so.

This will be a breaking change to users of the current "ignore includes" style. However, in my opinion this is fine. For one thing this tool is still in an early unstable phase. Also the expected and documented behavior stays the same. We simply exchange the interface to implement the desired behavior correctly.

As I am quite busy these days I can't promise any ETA on fixing this. I hope soonish and am confident it is for sure within 2022.

**Comment by matte1** [comment] 2022-12-03 15:30
Thanks Martis! If I understand the code correctly it should be fixed in filter_includes from parse_source? It seems like a simple fix if you would like me to make a PR for it.

Also I really appreciate this work; really excited to be using it!

**Comment by martis42** [comment] 2022-12-04 09:53
You are right, `filter_includes` is the function where the logic has to change.
Thanks a lot for you offer, I really appreciate it!

However, today I had some unexpected spare time available and already started fixing this. The logic is done, some cleanup triggered by touching this is still in progress. You can expect a fix to be merged soonish.

**Comment by martis42** [comment] 2022-12-04 12:10
I pushed a fix.

There are 2 breaking changes:
- One can no longer add patterns to the `*_paths` config fields
- Specifying an empty `ignore_include_paths` in the config disables ignoring the standard library headers

Documentation of the new behavior: https://github.com/martis42/depend_on_what_you_use#custom-header-ignore-list

Would you please try this out and provide feedback if the issue is now resolved for you? If it works for you, I would also cur a new release.

**Comment by matte1** [comment] 2022-12-04 16:01
Sorry I'm only familiar with using a release to include a bazel aspect. Whats the best way to test this prior to making a release?

**Comment by martis42** [comment] 2022-12-04 20:45
See this part of the README: https://github.com/martis42/depend_on_what_you_use#get-a-specific-commit

Essentially, GitHub allows you to download an archive for each commit of a repository.

The following will get you the current head
```sh
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

dwyu_version = "3afdcad3d12f33cec7c46a0d6337d8a55c47f6e5"
http_archive(
    name = "depend_on_what_you_use",
    sha256 = "cf9cba9cccbe3ce7d26861f8ffc72c995d5fed52ed39f130ae1eca5c639df0fc",  # optional
    strip_prefix = "depend_on_what_you_use-{}".format(dwyu_version),
    url = "https://github.com/martis42/depend_on_what_you_use/archive/{}.tar.gz".format(dwyu_version),
)

load("@depend_on_what_you_use//:dependencies.bzl", dwyu_dependencies = "public_dependencies")
dwyu_dependencies()
```

**Comment by matte1** [comment] 2022-12-05 15:07
Hmm maybe I'm doing something wrong but its failing to find the archive..
`WARNING: Download from https://github.com/martis42/depend_on_what_you_use/archive/refs/tags/3afdcad3d12f33cec7c46a0d6337d8a55c47f6e5.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found`

**Comment by matte1** [comment] 2022-12-05 15:17
That worked for me!!! Thanks Martis!

**Comment by martis42** [comment] 2022-12-05 20:39
Great :) I will cut a new release and close this issue afterwards.
Feel free to reach out again if you find more bugs or have a feature request.

**Closed** 2022-12-05 21:03 UTC
Labels: bug
